package asia.atmonline.myriskservice.enums.risk;

public enum RejectionReasonCode {
  NOT_CALLED, LOWINCOM, HIGHINCO, REJREGIO, CICNEGAT, FAILPTI1, REFCONFL, NEGADDRE, NEGEMPLO, DIFPERSO, PLEDGEID, CICNEGA3, CICNEGA4, PHONEOFF,
  RELPHON1, RELPHON2, FOROTHER, FROTHINF, CICNEGA2, NODOC002, CURRDELQ, UNCOPERA, RELOWAGE, NOSUPOCC, HISTDELQ, UNEMPLOY, NODEMAND, INCORACT,
  NOPICKUP, NODOC001, HIDEMAND, UNCONREL, SCORE2, APPLPROC, CUSDELQ1, CUSDELQ2, ACTLOAN, DDIDNMDB,
  DDNMBDID, DDOLDACC, SCR03CTF, REHIGHAG, BLCUSTID, BLCUSTBA, BLCUSTPH, BLREFEPH, BLWRKPH, DEDUBLID, DEDUBLNB, DEDUBLBA, NOSUPIND, NICNEG,
  TPCDPD15, FAILPTI, BRWTPC1, BRWTPC2, BRWWRK, SCORE1, JUICYSCORE,
  DDOVERDUE_a, DDREJECTS_a, DDAPLPROC_a, DDACTLOAN_a, BLBRW_MANUAL_a, NOSUPOCC2, SEONPHONE, SELFEMPL,
  NOBANKAC, NODOMENT,DOCUMFRD, NOVIDCALL, DIFPERSON, UNFINVER, FAILKYC, NORELINFO, NOWORKINFO, DUBLAPPL, OTHER, CLDWN2D,CLDWN5W, CLDWN10, DDCUSTBA,
  MAXDPD3, MAXDPD7, MAXDPD15, MAXDPD30, SUSPLSTNM, SUSPFSTNM, SUSPSECNM, SUSPID,
  SELFEMPL_PSN, SELFEMPL_PSC, PS_CUTOFF, PS_NOHIT, BLACKLIST, DDCUSTID,
  BLBRW_MANUAL, BLBRW_SYSTEM,
  JUICYDEDUP,EXPIRED,ACTIVE_LOAN,ACTIVE_APP,APPLIM_2D,APPLIM_5W,APPLIM_9M
}