version: "3"
services:
  my-service-risk:
    image: ${ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com/my-risk-service:${IMAGE_TAG}
    environment:
      - IMAGE_TAG
      - ACCOUNT_ID
    build: .
    container_name: my-service-risk
    restart: always