server:
  port: 8081
spring:
  flyway:
    baselineOnMigrate: ${BASELINE_ON_MIGRATE:true}
  #    locations: classpath:db/migration
  config:
    activate:
      on-profile: ${PROFILE:preprod}
  jpa:
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: ${SPRING_ALLOW_BEAN_OVERRIDING:true}
  cloud:
    compatibility-verifier:
      enabled: false
    aws:
      region:
        auto: false
        static: ap-southeast-1
      credentials:
        access-key: AKIAWH5BMXL72YM6U76D
        secret-key: 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
      stack:
        auto: false
  activemq:
    broker-url:

rules:
  basic:
    age-2-low: 21
    age-2-high: 70
    income: 350

datasource:
  risk:
    connectionTimeout: ${DATASOURCE_CONNECTION_TIMEOUT:60000}
    maximumPoolSize: ${DATASOURCE_POOL_SIZE:20}
    cachePrepStmts: ${DATASOURCE_CACHE_PREP_STMTS:true}
    prepStmtCacheSize: ${DATASOURCE_PREP_STMT_CACHE_SIZE:250}
    prepStmtCacheSqlLimit: ${DATASOURCE_PREP_STMT_CACHE_SQL_LIMIT:2048}
    useServerPrepStmts: ${DATASOURCE_USE_SERVER_PREP_STMTS:true}
    driverClassName: ${DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
#    url: jdbc:postgresql://${DB_MY_URL:localhost}:${DB_MY_PORT:5432}/${DB_MY_DATABASE:my_risk_service_local}?socketTimeout=30
#    username: ${DB_MY_LOGIN:postgres}
#    password: ${DB_MY_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_MY_URL}:${DB_MY_PORT}/${DB_MY_DATABASE}?socketTimeout=30
    username: ${DB_MY_LOGIN:postgres}
    password: ${DB_MY_PASSWORD:postgres}
  storage:
    connectionTimeout: ${DATASOURCE_STORAGE_CONNECTION_TIMEOUT:60000}
    maximumPoolSize: ${DATASOURCE_STORAGE_POOL_SIZE:20}
    cachePrepStmts: ${DATASOURCE_STORAGE_CACHE_PREP_STMTS:true}
    prepStmtCacheSize: ${DATASOURCE_STORAGE_PREP_STMT_CACHE_SIZE:250}
    prepStmtCacheSqlLimit: ${DATASOURCE_STORAGE_PREP_STMT_CACHE_SQL_LIMIT:2048}
    useServerPrepStmts: ${DATASOURCE_STORAGE_USE_SERVER_PREP_STMTS:true}
    driverClassName: ${DATASOURCE_STORAGE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: jdbc:postgresql://${DB_STORAGE_URL:my-dms-preprod-rds.ctoxc08s0evf.ap-southeast-1.rds.amazonaws.com}:${DB_STORAGE_PORT:5432}/${DB_STORAGE_DATABASE:dms}?socketTimeout=30
    username: ${DB_STORAGE_LOGIN:dms}
    password: ${DB_STORAGE_PASSWORD:gp6FSY23Ob8Ce4tJFgsK2lc9}

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY:AKIAWH5BMXL7TDQER3MH}
    secret-key: ${AWS_SECRET_KEY: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}
  default-task-executor:
    core-pool-size: ${CORE_POOL_SIZE:100}
    max-pool-size: ${MAX_POOL_SIZE:100}
    queue-capacity: ${QUEUE_CAPACITY:2}
    blocking-task-timeout: ${BLOCKING_TASK_TIMEOUT:1000}
  sqs:
    max-number-of-messages: ${SQS_MAX_NUMBER_OF_MESSAGES:10}
    back-off-time: ${SQS_BACK_OFF_TIME:60000}
    request:
      queue: ${REQUEST_QUEUES:my-risk-bl-request-preprod,my-risk-cooldown-request-preprod,my-risk-dedup-request-preprod,my-risk-basic-request-preprod,my-risk-score-request-preprod,my-risk-seon-fraud-request-preprod,my-risk-bureau-request-preprod,my-risk-final-request-preprod,my-risk-experian-request-preprod,my-risk-credit-history-request-preprod}
    blacklists:
      producer:
        queue-name: ${BL_RESPONSE_RISK_QUEUE:my-risk-bl-response-preprod}
    cooldown:
      producer:
        queue-name: ${COOLDOWN_RESPONSE_RISK_QUEUE:my-risk-cooldown-response-preprod}
    dedup:
      producer:
        queue-name: ${DEDUP_RESPONSE_RISK_QUEUE:my-risk-dedup-response-preprod}
    basic:
      producer:
        queue-name: ${BASIC_RESPONSE_RISK_QUEUE:my-risk-basic-response-preprod}
    score:
      producer:
        queue-name: ${SCORE_RESPONSE_RISK_QUEUE:my-risk-score-response-preprod}
    seon-fraud:
      producer:
        queue-name: ${SEON_FRAUD_RESPONSE_RISK_QUEUE:my-risk-seon-fraud-response-preprod}
    bureau:
      producer:
        queue-name: ${BUREAU_RESPONSE_RISK_QUEUE:my-risk-bureau-response-preprod}
    final:
      producer:
        queue-name: ${FINAL_RESPONSE_RISK_QUEUE:my-risk-final-response-preprod}

score:
  paths-to-properties:
    term:
      max: ${DMS_SCORE_TERM_MAX:dms.score.term.max}
      min: ${DMS_SCORE_TERM_MIN:dms.score.term.min}
    amount:
      max: ${DMS_SCORE_AMOUNT_MAX:dms.score.amount.max}
      min: ${DMS_SCORE_AMOUNT_MIN:dms.score.amount.min}
  cache:
    reload-time-minutes: 10
  ds:
    jdbcDriver: org.postgresql.Driver
    url: ${DB_SCORE_URL:lotus-preprod.ctoxc08s0evf.ap-southeast-1.rds.amazonaws.com}
    port: ${DB_SCORE_PORT:5432}
    database: ${DB_SCORE_DATABASE:lotus}
    username: ${DB_SCORE_USERNAME:risk_user_ro}
    password: ${DB_SCORE_PASSWORD:ZxamISdw1401ykn3M2vm}
  bitbucket:
    url:
      base: ${BITBUCKET_URL:https://api.bitbucket.org/2.0/repositories/my/external-score-files/src/master/projects/}
      il: ${BITBUCKET_PATH_TO_IL:my_scoreservice_preprod/il/app.sql}
      rs1: ${BITBUCKET_PATH_TO_RS1:my_scoreservice_preprod/rs1/app.sql}
      rs2: ${BITBUCKET_PATH_TO_RS2:my_scoreservice_preprod/rs2/app.sql}
      rs3: ${BITBUCKET_PATH_TO_RS3:my_scoreservice_preprod/rs3/app.sql}
    token: ${BASIC_AUTH_BITBUCKET:Basic c2VyX2FsZXU6QVRCQkR2RHFrUTRYdXdGS1U0UjhyUXpYdWg4YkU2RTNFN0E2}

experian:
  base-url: ${EXPERIAN_BASE_URL:https://b2buat.experian.com.my/index.php/b2bgateway}
  ccris:
    url: ${EXPERIAN_CCRIS_SEARCH_URL:xxx}
  retrieve-report:
    url: ${EXPERIAN_RETRIEVE_REPORT_URL:xxx}

seon-fraud:
  #  !PROD! license-key: ${SEON_LICENSE_KEY:6fb041e6-86ac-433e-93f6-ab128c72bceb}
  license-key: ${SEON_LICENSE_KEY:1856407c-4c65-43b7-b597-70ed5f228b0d}
  base-url: ${SEON_BASE_URL:https://api.seon.io}
  paths-to-properties:
    timeout: ${DMS_SEON_TIMEOUT:dms.seon.timeout}
    requests-limit: ${DMS_SEON_REQUESTS_LIMIT:dms.seon.requests.limit}
    ip:
      api-version: ${DMS_SEON_IP_API_VERSION:dms.seon.ip.api.version}
    email:
      enable: ${DMS_SEON_EMAIL_ENABLE:dms.seon.email.enable}
      api-version: ${DMS_SEON_EMAIL_API_VERSION:dms.seon.email.api.version}
    phone:
      enable: ${DMS_SEON_PHONE_ENABLE:dms.seon.phone.enable}
      api-version: ${DMS_SEON_PHONE_API_VERSION:dms.seon.phone.api.version}
      stop-factor:
        enable: ${DMS_SEON_PHONE_STOP_FACTOR_ENABLE:dms.seon.phone.stop.factor.enable}
    fingerprint:
      enable: ${DMS_SEON_FINGERPRINT_ENABLE:dms.seon.fingerprint.enable}
  default:
    timeout: ${DEFAULT_SEON_TIMEOUT:30000}
    requests-limit: ${DEFAULT_SEON_REQUESTS_LIMIT:30}
    ip:
      api-version: ${DEFAULT_SEON_IP_API_VERSION:1.1}
    email:
      enable: ${DEFAULT_SEON_EMAIL_ENABLE:true}
      api-version: ${DEFAULT_SEON_EMAIL_API_VERSION:2.2}
    phone:
      enable: ${DEFAULT_SEON_PHONE_ENABLE:true}
      api-version: ${DEFAULT_SEON_PHONE_API_VERSION:1.3}
      stop-factor:
        enable: ${DEFAULT_SEON_PHONE_STOP_FACTOR_ENABLE:false}
    fingerprint:
      enable: ${DEFAULT_SEON_FINGERPRINT_ENABLE:true}
