DROP TABLE IF EXISTS credit_bureau_info;
CREATE TABLE IF NOT EXISTS credit_bureau_info (
  id serial PRIMARY KEY,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  application_id bigint,
  bureau_id int,
  ccris_search_request_dttm timestamp,
  ccris_search_request_json text,
  ccris_search_response_status varchar(50),
  ccris_search_error_code varchar(50),
  ccris_search_response_dttm timestamp,
  ccris_search_response_json text,
  ccris_search_crefid bigint,
  ccris_search_entitykey varchar(50),
  ccris_confirm_request_dttm timestamp,
  ccris_confirm_request_json text,
  ccris_confirm_response_status varchar(50),
  ccris_confirm_error_code text,
  ccris_confirm_response_dttm timestamp,
  ccris_confirm_response_json text,
  ccris_confirm_token1 varchar(200),
  ccris_confirm_token2 varchar(200),
  ccris_report_request_dttm timestamp,
  ccris_report_request_json text,
  ccris_report_response_status varchar(50),
  ccris_report_error_code varchar(50),
  ccris_report_response_dttm timestamp,
  ccris_report_response_json text,
  "score" int,
  score_grade varchar(50)
);

DROP TABLE IF EXISTS credit_bureau_info_details;
CREATE TABLE IF NOT EXISTS credit_bureau_info_details (
  id serial PRIMARY KEY,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  ccris_response_id bigint,
  master_id varchar(100),
  "date" varchar(100),
  capacity varchar(50),
  lender_type varchar(50),
  credit_limit bigint,
  legal_status varchar(50),
  legal_status_date varchar(100),
  master_collateral_type varchar(50),
  financial_group_resident_status varchar(50),
  master_collateral_type_code varchar(50),
  "status" varchar(50),
  restructure_reschedule_date varchar(100),
  facility varchar(50),
  total_outstanding_balance varchar(200),
  total_outstanding_balance_bnm varchar(200),
  balance_updated_date varchar(100),
  installment_amount varchar(200),
  principle_repayment_term varchar(100),
  sub_account_collateral_type varchar(50),
  sub_account_collateral_type_code varchar(50),
  credit_position varchar(50)
);